Stacking
AshtonFox/Donnarex pull request #29
Opened 2020-05-05 23:23 UTC by RenardQueenston

:cl:
rscadd: Добавлены спрайты для бинтов, мазей и advanced патчей, отображающие их количество. Вернул возможность накладывать шину на голову, тело и гроин.
/:cl:

2020-05-05 23:30 UTC, RenardQueenston commented
Ну и соответственно впилена функция отображения этих спрайтов. Странно, что на ориг-торче этого нет... Думаю стоит им скинуть, чтобы не было конфликтов.

2020-05-05 23:31 UTC, AshtonFox commented
Ага, и будет как в прошлый раз. Но можешь попробовать, конечно же. Но для этого тебе нужен форк Бэя.

2020-05-05 23:32 UTC, RenardQueenston commented
Форк бея есть в организации, так что это не проблема.

2020-05-06 00:22 UTC, AshtonFox requested changes

2020-05-06 00:22 UTC, AshtonFox commented on code/game/objects/items/stacks/medical.dm
> +			playsound(src, pick(apply_sounds), 25)
Приведёт к повторному проигрыванию звука после завершения операции, что нам, конечно же, не нужно _(см.  наличие того же процесса в строке 246)_
```suggestion
```

2020-05-06 00:22 UTC, AshtonFox commented on frontier/code/game/objects/items/stacks/medical_vr.dm
> +	icon = 'icons/obj/medical_kits.dmi'
Дубликат переменной, заданной на более высоком уровне, без изменений. Зачем?
```suggestion
```

2020-05-06 00:22 UTC, AshtonFox commented on frontier/code/game/objects/items/stacks/medical_vr.dm
> +/obj/item/stack/medical/advanced
```suggestion
```

2020-05-06 00:22 UTC, AshtonFox commented on frontier/code/game/objects/items/stacks/medical_vr.dm
> +	icon = 'icons/obj/medical_kits.dmi'
То же, что и вверху.
```suggestion
```

2020-05-06 00:22 UTC, AshtonFox commented on frontier/code/game/objects/items/stacks/medical_vr.dm
> +/obj/item/stack/medical/bruise_pack
```suggestion
```

2020-05-06 00:22 UTC, AshtonFox commented on frontier/code/game/objects/items/stacks/medical_vr.dm
> +	icon = 'icons/obj/medical_kits.dmi'
```suggestion
```

2020-05-06 00:22 UTC, AshtonFox commented on frontier/code/game/objects/items/stacks/medical_vr.dm
> +/obj/item/stack/medical/ointment
```suggestion
```

2020-05-06 00:23 UTC, RenardQueenston commented on frontier/code/game/objects/items/stacks/medical_vr.dm
> +/obj/item/stack/medical/ointment
Нахуя

2020-05-06 00:24 UTC, AshtonFox commented on frontier/code/game/objects/items/stacks/medical_vr.dm
> +/obj/item/stack/medical/ointment
Прочти остальные, что выше, это одна и та же проблема.

2020-05-06 00:25 UTC, RenardQueenston commented on frontier/code/game/objects/items/stacks/medical_vr.dm
> +/obj/item/stack/medical/ointment
Пойду на локалку тестить опять

2020-05-06 00:48 UTC, RenardQueenston commented on code/game/objects/items/stacks/medical.dm
> +			playsound(src, pick(apply_sounds), 25)
Почему вообще не перенести проигрывание звука на конец операции..

2020-05-06 02:32 UTC, RenardQueenston commented on code/game/objects/items/stacks/medical.dm
> +			playsound(src, pick(apply_sounds), 25)
Я перенёс, уберите это как-нибудь.

2020-05-06 07:10 UTC, AshtonFox approved these changes

2020-05-06 07:15 UTC, merged